# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  @pytest.mark.parametrize("text", ("сережки", "серіжкі", "сержки"))

  def test_search(self, text):
    self.driver.get("https://a-shop.ua/")
    self.driver.set_window_size(1268, 724)
    self.driver.find_element(By.ID, "search").click()
    self.driver.find_element(By.ID, "search").click()
    self.driver.find_element(By.ID, "search").send_keys(text)
    self.driver.find_element(By.ID, "search").send_keys(Keys.ENTER)

    WebDriverWait(self.driver, 10).until(
      expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#maincontent")))
    elements = self.driver.find_elements(By.PARTIAL_LINK_TEXT, (text.capitalize()))
    assert len(elements) > 2, f"Total items of search results is less then 2"

    # elements = self.find_element_by_xpath("//span[@data-bind ='text: index.totalItems']")
    #                                       # "//div[span/@data-bind ='text: index.totalItems']")
    # assert len(elements) > 2, f"Total items of search results is less then 2"


  
